name: epitope1d
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python=3.6.13
  - joblib=1.2.0
  - pip
  - pandas
  - numpy
  - pip:
    - aaindex==0.0.2
    - scikit-learn==0.24.1